#!/bin/bash
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2016 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault

OMV_MKCONF_SCRIPTS_DIR=${OMV_MKCONF_SCRIPTS_DIR:-"/usr/share/openmediavault/mkconf"}

NETRC_CONFIG="/root/.netrc"
NETRC_SECTIONNAME="omvextras"
NETRC_EXTENSIONS_DIR="${OMV_MKCONF_SCRIPTS_DIR}/netrc.d"}

# Execute all scripts building the custom netrc configuration.
netrccfg=$(echo -n "# >>> [${NETRC_SECTIONNAME}]\n"; run-parts --exit-on-error ${NETRC_EXTENSIONS_DIR} | perl -p -e 's/\n/\\n/g'; echo -n "# <<< [${NETRC_SECTIONNAME}]")

# Append custom netrc configuration if not still present or replace existing one.
if ! grep -E "^# >>> \[${NETRC_SECTIONNAME}\]\s*$" ${NETRC_CONFIG} >/dev/null; then
    echo -e "${netrccfg}" >> ${NETRC_CONFIG}
else
    sed -i "/# >>> \[${NETRC_SECTIONNAME}\]/,/# <<< \[${NETRC_SECTIONNAME}\]/ c ${netrccfg}" ${NETRC_CONFIG}
fi

chmod 600 ${NETRC_CONFIG}
